### ISSUE TITLE
How far is this sub-project?

### ISSUE THREAD

**Issue by Phlosioneer** [Franiac/SharpLoader#2]
Is it at a stage where it can perform some functionality, or is it still purely code-writing and unable to be tested? I'm interested in trying to contribute, or at least to hack on it, and I don't see how to get a test harness setup, or to make Twitch Leacher use a build of this.

**Comment by Franiac** [comment]
currently my non-commited status is that it can handle a single download... no pause/resume or anything else, no multithreading. long way to go. i become a father in 8 weeks... there are new priorities and responsibilities.

**Comment by Phlosioneer** [comment]
Alright, I totally understand. Just wanted to see if I could help. Congrats, by the way!
